import * as fs from 'node:fs';
import * as path from 'node:path';

function parseCssTokens(cssPath: string): { root: Record<string, string>; print: Record<string, string> } {
  const content = fs.readFileSync(cssPath, 'utf-8');

  // Separate root block from @media print block
  const printMatch = content.match(/@media\s+print\s*\{([\s\S]*?)\}\s*\}/);
  const printContent = printMatch ? printMatch[1] : '';
  const rootContent = content.replace(/@media\s+print\s*\{[\s\S]*?\}\s*\}/, '');

  function extractTokens(block: string): Record<string, string> {
    const tokens: Record<string, string> = {};
    const regex = /--([a-zA-Z0-9_-]+):\s*([^;]+);/g;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(block)) !== null) {
      tokens[match[1].trim()] = match[2].trim();
    }
    return tokens;
  }

  const rootTokens = extractTokens(rootContent);
  const printTokens = extractTokens(printContent);

  function resolve(val: string, dict: Record<string, string>): string {
    const varRegex = /var\(--([a-zA-Z0-9_-]+)\)/g;
    return val.replace(varRegex, (_, refKey) => {
      if (dict[refKey]) {
        return resolve(dict[refKey], dict);
      }
      if (rootTokens[refKey]) {
        return resolve(rootTokens[refKey], rootTokens);
      }
      return val;
    });
  }

  const resolvedRoot: Record<string, string> = {};
  for (const [k, v] of Object.entries(rootTokens)) {
    resolvedRoot[k] = resolve(v, rootTokens);
  }

  const resolvedPrint: Record<string, string> = {};
  for (const [k, v] of Object.entries(printTokens)) {
    resolvedPrint[k] = resolve(v, { ...rootTokens, ...printTokens });
  }

  return { root: resolvedRoot, print: resolvedPrint };
}

export function exportTokens() {
  const cssPath = path.resolve(process.cwd(), 'app/tokens.css');
  const { root: tokens, print: printTokens } = parseCssTokens(cssPath);

  const outDir = path.resolve(process.cwd(), 'lib');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const code = `/**
 * DORICE SMART ACADEMY - GENERATED TOKENS
 * Auto-generated by scripts/export-tokens.ts from app/tokens.css
 *
 * DO NOT EDIT DIRECTLY.
 * Used for React-PDF documents, Resend email templates, and ChartJS/Recharts.
 */

export const tokens = {
  raw: ${JSON.stringify(tokens, null, 2)} as const,
  printOverrides: ${JSON.stringify(printTokens, null, 2)} as const,

  colors: {
    surface: {
      bg: '${tokens['color-bg']}',
      surface: '${tokens['color-surface']}',
      surfaceMuted: '${tokens['color-surface-muted']}',
      surfaceHighlight: '${tokens['color-surface-highlight']}',
      border: '${tokens['color-border']}',
      borderStrong: '${tokens['color-border-strong']}',
    },
    text: {
      default: '${tokens['color-text']}',
      muted: '${tokens['color-text-muted']}',
      inverse: '${tokens['color-text-inverse']}',
      link: '${tokens['color-link']}',
      linkHover: '${tokens['color-link-hover']}',
    },
    primary: {
      default: '${tokens['color-primary']}',
      hover: '${tokens['color-primary-hover']}',
      active: '${tokens['color-primary-active']}',
      fg: '${tokens['color-primary-fg']}',
      soft: '${tokens['color-primary-soft']}',
      navBg: '${tokens['color-nav-bg']}',
      navFg: '${tokens['color-nav-fg']}',
      tableHeaderBg: '${tokens['color-table-header-bg']}',
      tableHeaderFg: '${tokens['color-table-header-fg']}',
    },
    accent: {
      default: '${tokens['color-accent']}',
      hover: '${tokens['color-accent-hover']}',
      active: '${tokens['color-accent-active']}',
      fg: '${tokens['color-accent-fg']}',
      soft: '${tokens['color-accent-soft']}',
      focusRing: '${tokens['color-focus-ring']}',
    },
    status: {
      success: {
        solid: '${tokens['color-success-solid']}',
        soft: '${tokens['color-success-soft']}',
        border: '${tokens['color-success-border']}',
        fg: '${tokens['color-success-fg']}',
      },
      warning: {
        solid: '${tokens['color-warning-solid']}',
        soft: '${tokens['color-warning-soft']}',
        border: '${tokens['color-warning-border']}',
        fg: '${tokens['color-warning-fg']}',
      },
      danger: {
        solid: '${tokens['color-danger-solid']}',
        soft: '${tokens['color-danger-soft']}',
        border: '${tokens['color-danger-border']}',
        fg: '${tokens['color-danger-fg']}',
      },
      info: {
        solid: '${tokens['color-info-solid']}',
        soft: '${tokens['color-info-soft']}',
        border: '${tokens['color-info-border']}',
        fg: '${tokens['color-info-fg']}',
      },
    },
    levels: {
      ee: {
        solid: '${tokens['level-ee']}',
        soft: '${tokens['level-ee-soft']}',
        fg: '${tokens['level-ee-fg']}',
        label: 'Exceeding Expectations',
        code: 'EE',
        stars: 4,
      },
      me: {
        solid: '${tokens['level-me']}',
        soft: '${tokens['level-me-soft']}',
        fg: '${tokens['level-me-fg']}',
        label: 'Meeting Expectations',
        code: 'ME',
        stars: 3,
      },
      ae: {
        solid: '${tokens['level-ae']}',
        soft: '${tokens['level-ae-soft']}',
        fg: '${tokens['level-ae-fg']}',
        label: 'Approaching Expectations',
        code: 'AE',
        stars: 2,
      },
      be: {
        solid: '${tokens['level-be']}',
        soft: '${tokens['level-be-soft']}',
        fg: '${tokens['level-be-fg']}',
        label: 'Below Expectations',
        code: 'BE',
        stars: 1,
      },
    },
    charts: [
      '${tokens['chart-1']}',
      '${tokens['chart-2']}',
      '${tokens['chart-3']}',
      '${tokens['chart-4']}',
      '${tokens['chart-5']}',
      '${tokens['chart-6']}',
    ],
  },
} as const;

export type DesignTokens = typeof tokens;
`;

  const outPath = path.resolve(outDir, 'tokens.generated.ts');
  fs.writeFileSync(outPath, code, 'utf-8');
  console.log(`Generated typed tokens written to ${outPath}`);
}

exportTokens();
