import * as fs from 'node:fs';
import * as path from 'node:path';
import { converter, formatHex, interpolate } from 'culori';

const toOklch = converter('oklch');
const toRgb = converter('rgb');

// Anchors from Section 3.1 & sampled from assets
export const ANCHORS = {
  navy: '#123F70',
  marigold: '#E8681C',
  marigoldStrong: '#C4530F',
  schoolRed: '#C8282D',
  teal: '#1799B0',
  tealStrong: '#0E7C91',
  cream: '#F7F0E1',
  chalkButter: '#F3E9B8',
  uniformBlue: '#3B5FB4',
  flagGreen: '#1E7B45',
  peach: '#F2C7A0',
  ink: '#10243C',
};

// Target lightness steps for OKLCH scale 50..950
const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;

function generateOklchScale(anchorHex: string, anchorStep = 500) {
  const oklch = toOklch(anchorHex);
  if (!oklch) throw new Error(`Invalid anchor hex: ${anchorHex}`);

  const targetLightness: Record<number, number> = {
    50: 0.97,
    100: 0.93,
    200: 0.86,
    300: 0.77,
    400: 0.67,
    500: oklch.l, // Anchor at 500
    600: oklch.l * 0.85,
    700: oklch.l * 0.70,
    800: oklch.l * 0.54,
    900: oklch.l * 0.38,
    950: oklch.l * 0.26,
  };

  const scale: Record<number, string> = {};

  for (const step of STEPS) {
    if (step === anchorStep) {
      scale[step] = anchorHex.toUpperCase();
      continue;
    }

    const l = targetLightness[step];
    // Slightly adjust chroma for very light / very dark ends
    let c = oklch.c;
    if (step === 50) c = oklch.c * 0.18;
    else if (step === 100) c = oklch.c * 0.35;
    else if (step === 200) c = oklch.c * 0.6;
    else if (step === 900) c = oklch.c * 0.65;
    else if (step === 950) c = oklch.c * 0.45;

    const color = {
      mode: 'oklch' as const,
      l: Math.min(0.99, Math.max(0.1, l)),
      c,
      h: oklch.h,
    };

    const hex = formatHex(color);
    scale[step] = (hex || anchorHex).toUpperCase();
  }

  return scale;
}

// Special gold scale anchored on chalkButter at 100 and a rich deep amber at 700
function generateGoldScale() {
  const butter = toOklch(ANCHORS.chalkButter)!;
  const darkGold = toOklch('#8A6A00')!;

  const scale: Record<number, string> = {
    50: '#FDFBF2',
    100: ANCHORS.chalkButter.toUpperCase(),
    200: '#EBDD98',
    300: '#DEC96B',
    400: '#CEB23C',
    500: '#B89B1F',
    600: '#9E810C',
    700: '#8A6A00',
    800: '#6B5200',
    900: '#4D3A00',
    950: '#332700',
  };
  return scale;
}

// Special cream scale for warm surfaces
function generateCreamScale() {
  return {
    50: '#FCF9F3',
    100: '#F7F0E1', // Anchor
    200: '#EFE3CA',
    300: '#E5D3AF',
    400: '#DAC091',
    500: '#CEAA71',
    600: '#BD9454',
    700: '#9A743C',
    800: '#75562C',
    900: '#523A1E',
    950: '#342412',
  };
}

// Special ink scale for rich body text
function generateInkScale() {
  return {
    50: '#F2F4F7',
    100: '#E1E6ED',
    200: '#C2CBD8',
    300: '#9EAEC2',
    400: '#6E839F',
    500: '#49607D',
    600: '#324761',
    700: '#233449',
    800: '#17273A',
    900: ANCHORS.ink.toUpperCase(), // Anchor: #10243C
    950: '#0A1728',
  };
}

export function generateTokensCss(): string {
  const navy = generateOklchScale(ANCHORS.navy);
  const marigold = generateOklchScale(ANCHORS.marigold);
  const teal = generateOklchScale(ANCHORS.teal);
  const red = generateOklchScale(ANCHORS.schoolRed);
  const green = generateOklchScale(ANCHORS.flagGreen);
  const blue = generateOklchScale(ANCHORS.uniformBlue);
  const gold = generateGoldScale();
  const cream = generateCreamScale();
  const ink = generateInkScale();

  let css = `/**
 * DORICE SMART ACADEMY - DESIGN TOKENS
 * Auto-generated by scripts/generate-palette.ts
 *
 * DO NOT EDIT DIRECTLY. Run \`npm run tokens:generate\` to update.
 * Motto: "Inspire, Achieve, Flourish"
 */

:root {
  /* ==========================================================================
     TIER 1: PRIMITIVE TOKENS (Never use directly in feature components)
     ========================================================================== */

  /* Navy Scale (Primary / 30% Structure) */
${STEPS.map((s) => `  --navy-${s}: ${navy[s]};`).join('\n')}

  /* Marigold Scale (Signature Accent / 10% Call to Action) */
${STEPS.map((s) => `  --marigold-${s}: ${marigold[s]};`).join('\n')}
  --marigold-strong: ${ANCHORS.marigoldStrong.toUpperCase()};

  /* Teal Scale (Supporting / Info / CBC Meeting) */
${STEPS.map((s) => `  --teal-${s}: ${teal[s]};`).join('\n')}
  --teal-strong: ${ANCHORS.tealStrong.toUpperCase()};

  /* School Red Scale (Danger / Arrears / CBC Below) */
${STEPS.map((s) => `  --red-${s}: ${red[s]};`).join('\n')}

  /* Flag Green Scale (Success / Paid / CBC Exceeding) */
${STEPS.map((s) => `  --green-${s}: ${green[s]};`).join('\n')}

  /* Gold Scale (Warning / Partial / CBC Approaching) */
${STEPS.map((s) => `  --gold-${s}: ${gold[s]};`).join('\n')}

  /* Uniform Blue Scale (Plaid Pattern / Secondary Charts) */
${STEPS.map((s) => `  --blue-${s}: ${blue[s]};`).join('\n')}

  /* Cream Scale (Warm Surfaces / 60% Background) */
${STEPS.map((s) => `  --cream-${s}: ${cream[s]};`).join('\n')}

  /* Ink Scale (Rich Body Text / High Contrast) */
${STEPS.map((s) => `  --ink-${s}: ${ink[s]};`).join('\n')}

  /* Peach Single Token (Avatars / Illustrations) */
  --peach-500: ${ANCHORS.peach.toUpperCase()};
  --chalk-butter: ${ANCHORS.chalkButter.toUpperCase()};

  /* ==========================================================================
     TIER 2: SEMANTIC TOKENS (The ONLY tokens feature code may reference)
     ========================================================================== */

  /* Surfaces (The 60% dominant canvas) */
  --color-bg: var(--cream-100);
  --color-surface: #FFFFFF;
  --color-surface-muted: var(--cream-50);
  --color-surface-highlight: var(--chalk-butter);
  --color-border: var(--cream-200);
  --color-border-strong: var(--cream-300);

  /* Text & Typography */
  --color-text: var(--ink-900);
  --color-text-muted: var(--ink-500);
  --color-text-inverse: #FFFFFF;
  --color-link: var(--navy-500);
  --color-link-hover: var(--navy-700);

  /* Structure (The 30% brand presence) */
  --color-primary: var(--navy-500);
  --color-primary-hover: var(--navy-600);
  --color-primary-active: var(--navy-700);
  --color-primary-fg: #FFFFFF;
  --color-primary-soft: var(--navy-50);
  --color-nav-bg: var(--navy-500);
  --color-nav-fg: #FFFFFF;
  --color-table-header-bg: var(--navy-500);
  --color-table-header-fg: #FFFFFF;

  /* Accent (The 10% CTA / Focus budget) */
  --color-accent: var(--marigold-strong);
  --color-accent-hover: var(--marigold-700);
  --color-accent-active: var(--marigold-800);
  --color-accent-fg: #FFFFFF;
  --color-accent-soft: var(--marigold-50);
  --color-focus-ring: var(--marigold-strong);

  /* Status Tokens */
  --color-success-solid: var(--green-500);
  --color-success-soft: var(--green-50);
  --color-success-border: var(--green-200);
  --color-success-fg: var(--green-800);

  --color-warning-solid: var(--gold-600);
  --color-warning-soft: var(--gold-50);
  --color-warning-border: var(--gold-200);
  --color-warning-fg: var(--gold-800);

  --color-danger-solid: var(--red-500);
  --color-danger-soft: var(--red-50);
  --color-danger-border: var(--red-200);
  --color-danger-fg: var(--red-800);

  --color-info-solid: var(--teal-strong);
  --color-info-soft: var(--teal-50);
  --color-info-border: var(--teal-200);
  --color-info-fg: var(--teal-800);

  /* CBC Performance Levels */
  --level-ee: var(--green-500);
  --level-ee-soft: var(--green-50);
  --level-ee-fg: var(--green-800);

  --level-me: var(--teal-strong);
  --level-me-soft: var(--teal-50);
  --level-me-fg: var(--teal-800);

  --level-ae: var(--gold-600);
  --level-ae-soft: var(--gold-50);
  --level-ae-fg: var(--gold-800);

  --level-be: var(--red-500);
  --level-be-soft: var(--red-50);
  --level-be-fg: var(--red-800);

  /* Data Visualisation Series (Order: navy, teal, marigold, blue, green, red) */
  --chart-1: var(--navy-500);
  --chart-2: var(--teal-500);
  --chart-3: var(--marigold-500);
  --chart-4: var(--blue-500);
  --chart-5: var(--green-500);
  --chart-6: var(--red-500);

  /* shadcn/ui Standard Variable Mapping */
  --background: var(--color-bg);
  --foreground: var(--color-text);
  --card: var(--color-surface);
  --card-foreground: var(--color-text);
  --popover: var(--color-surface);
  --popover-foreground: var(--color-text);
  --primary: var(--color-primary);
  --primary-foreground: var(--color-primary-fg);
  --secondary: var(--color-surface-muted);
  --secondary-foreground: var(--color-text);
  --muted: var(--color-surface-muted);
  --muted-foreground: var(--color-text-muted);
  --accent: var(--color-accent);
  --accent-foreground: var(--color-accent-fg);
  --destructive: var(--color-danger-solid);
  --destructive-foreground: #FFFFFF;
  --border: var(--color-border);
  --input: var(--color-border);
  --ring: var(--color-focus-ring);
  --radius: 0.625rem; /* 10px standard radius */
}

/* @media print override for high contrast greyscale-friendly printing */
@media print {
  :root {
    --color-bg: #FFFFFF;
    --color-surface: #FFFFFF;
    --color-surface-muted: #F8F9FA;
    --color-surface-highlight: #FFFFFF;
    --color-border: #D1D5DB;
    --color-border-strong: #9CA3AF;
    --color-text: #111827;
    --color-text-muted: #4B5563;
    --color-primary: #123F70;
    --color-primary-soft: #F3F4F6;
    --color-nav-bg: #123F70;
    --color-nav-fg: #FFFFFF;
    --color-accent: #123F70;
    --color-accent-fg: #FFFFFF;
  }
}
`;

  return css;
}

async function run() {
  const css = generateTokensCss();
  const targetPath = path.resolve(process.cwd(), 'app/tokens.css');
  fs.writeFileSync(targetPath, css, 'utf-8');
  console.log(`Generated design tokens written to ${targetPath}`);
}

run();
